# Generated by Django 4.1.7 on 2023-02-23 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'marchmadnessapp_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('total_score', models.IntegerField()),
            ],
            options={
                'db_table': 'marchmadnessapp_member',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MemberPlayer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'marchmadnessapp_member_player',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('points', models.IntegerField()),
            ],
            options={
                'db_table': 'marchmadnessapp_player',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'managed': False},
        ),
    ]
