# Generated by Django 4.1.7 on 2023-02-23 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0002_group_member_memberplayer_player_alter_team_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='team',
            table='marchmadnessapp_team',
        ),
    ]
