# Generated by Django 4.1.7 on 2023-02-23 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0003_alter_team_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('players', models.ManyToManyField(to='draft.player')),
            ],
        ),
    ]
