# Generated by Django 4.1.7 on 2023-02-23 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0004_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='group_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='peoples', to='draft.group'),
        ),
    ]
