# Generated by Django 4.1.7 on 2023-02-23 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0005_people_group_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='MemberPlayer',
        ),
    ]
