# Generated by Django 4.1.7 on 2023-02-23 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0006_delete_member_delete_memberplayer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='people',
            options={'managed': False},
        ),
    ]
