# Generated by Django 4.1.7 on 2023-02-25 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0008_alter_people_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={},
        ),
        migrations.AlterModelOptions(
            name='people',
            options={},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={},
        ),
    ]
