# Generated by Django 4.1.7 on 2023-02-27 03:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0009_alter_group_options_alter_people_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='people',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='group',
            name='draft_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), default=list, size=None),
        ),
    ]
