# Generated by Django 4.1.7 on 2023-03-12 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0011_group_draft_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='last_draft_pick',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
