# Generated by Django 4.1.7 on 2023-03-12 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0012_group_last_draft_pick'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='last_person_picking',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
