# Generated by Django 4.1.7 on 2023-03-12 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0014_delete_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('knocked_out', models.BooleanField()),
            ],
            options={
                'db_table': 'marchmadnessapp_team',
                'managed': False,
            },
        ),
    ]
